Recentering
OpenChamp/_original_client pull request #14
Opened 2024-05-26 17:33 UTC by Humungus-Fungus

Pressing space now centers cam on champ instead of the center of the map.
Pressing Y toggles this.

2024-05-26 20:50 UTC, noah1510 commented
You will have to reimplement this after #13 is merged. Both of you properly reformatted the player script but the other pr is for the whole project.

2024-05-26 20:53 UTC, noah1510 commented
Also all camera controls should be purely client only. Why is there server communication in camera movement? The clients don't need the server permission to move their camera where they want it to be.

2024-05-27 15:23 UTC, Humungus-Fungus commented
Updated to work with #13 and now uses the names of the champion nodes to get their pid instead of asking the server.

2024-05-27 15:45 UTC, noah1510 requested changes
Remove Player.gd and ServerListener.gd since they no longer exist upstream.
Otherwise it looks good.

I will rework some of the centering logic in the future to support semi-locked camera controls. For that the center_cam will be reworked into a get_target_position which returns the follow target. Either you do that now or I will do that later.
Also the is_cam_centered option should be a config option but again, I can do that in the future.

2024-05-27 17:02 UTC, Humungus-Fungus commented
Oops, didn't even notice the change in names. Reworked center_cam. Changed is_cam_centered into a config setting, now you have the option to change the center toggle through settings or with Y, both work.

2024-05-27 17:32 UTC, noah1510 requested changes

2024-05-27 17:32 UTC, noah1510 commented on Scripts/config.gd
> +func set_cam_centered(new_value: float):
should be bool

2024-05-27 17:32 UTC, noah1510 commented
Besides the wrong type this is good to go

2024-05-27 17:54 UTC, noah1510 approved these changes

2024-05-28 12:07 UTC, merged